list(APPEND MCC_COMPILE_OPTIONS -Wno-deprecated)
list(APPEND MCC_COMPILE_OPTIONS -frtti)

list(JOIN MCC_COMPILE_OPTIONS " " MCC_COMPILE_OPTIONS_STRING)
message(STATUS "[mcc] Compile options: " ${MCC_COMPILE_OPTIONS_STRING})